# Use Node base image
FROM node:20.11.0

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy source code
COPY . .

# Expose React dev server port
EXPOSE 5173

# Run app in development mode
CMD ["npm", "start"]
